import type { Content } from '../types'

export const services = {
  index: {
    hero: {
      eyebrow: 'Our services',
      title: 'Creative and production services in Mangaluru',
      lead: 'Social media, video, editing, photography, events, studio space and campaigns. Instead of treating these as completely separate services, we bring them together to create a more connected brand experience.',
    },
    listTitle: 'Eight services, one creative partner',
    closing:
      'A client may come to us looking for social media management and eventually need a campaign, video production, event coverage or a complete content strategy. Our role is to understand the bigger picture and build the right creative solution around it.',
  },
  detail: {
    capabilitiesTitle: 'What it can include',
    relatedTitle: 'Often paired with',
    faqTitle: 'Questions we hear',
    ctaTitle: 'Have a project in mind?',
    ctaBody:
      'Whether you already have a detailed brief or only have an idea, you can start a conversation with us.',
    backToServices: 'All services',
    serviceLabel: 'Service {number}',
  },
  items: [
    {
      slug: 'social-media-management',
      name: 'Social Media Management',
      shortName: 'Social media',
      summary: 'A social presence that feels consistent, recognisable and relevant.',
      intro: [
        'We help brands build and maintain a consistent presence across social media platforms.',
      ],
      capabilitiesIntro: 'Our social media work can include:',
      capabilities: [
        'Social media strategy',
        'Content planning',
        'Creative concepts',
        'Reels',
        'Short-form videos',
        'Static creatives',
        'Carousels',
        'Stories',
        'Content writing',
        'Captions',
        'Publishing',
        'Page management',
        'Community management',
        'Content optimisation',
        'Monthly performance tracking',
        'Campaign-based content',
      ],
      body: [
        "We don't simply fill a content calendar.",
        'We work to understand the brand, its audience, its communication style and its objectives before developing content.',
      ],
      outcome:
        'Our goal is to create a social presence that feels consistent, recognisable and relevant.',
      related: ['brand-campaigns', 'video-editing', 'photography'],
      faqIds: ['social', 'size'],
      image: 'serviceSocial',
      seo: {
        title: 'Social Media Management in Mangaluru',
        description:
          'Social media management in Mangaluru: strategy, content planning, reels, carousels, captions, publishing and community management for a consistent brand.',
        keywords: [
          'social media management Mangaluru',
          'reels',
          'content planning',
          'Dakshina Kannada',
        ],
        ogAlt: 'Social Media Management by Powerhouse Studios, Mangaluru',
      },
    },
    {
      slug: 'video-production',
      name: 'Video Production',
      shortName: 'Video production',
      summary: 'Video projects from concept to final delivery.',
      intro: [
        'Video is one of the most powerful ways for a brand to communicate.',
        'Powerhouse handles video projects from concept to final delivery.',
      ],
      capabilitiesIntro: 'Our production capabilities include:',
      capabilities: [
        'Concept development',
        'Creative direction',
        'Script development',
        'Pre-production planning',
        'Location shoots',
        'Studio shoots',
        'Interviews',
        'Talking-head videos',
        'Product videos',
        'Brand films',
        'Corporate videos',
        'Promotional videos',
        'Social media videos',
        'Event films',
        'Reels',
        'Campaign videos',
        'YouTube content',
        'Podcast video production',
      ],
      body: [],
      outcome:
        "We focus on the complete production process so clients don't have to coordinate multiple teams for every stage of a project.",
      related: ['video-editing', 'studio-rentals', 'brand-campaigns'],
      faqIds: ['entire', 'outside'],
      image: 'serviceVideoProduction',
      seo: {
        title: 'Video Production in Mangaluru',
        description:
          'Video production in Mangaluru from concept to final delivery: brand films, product and corporate videos, interviews, reels, YouTube and podcast video.',
        keywords: ['video production Mangaluru', 'brand film', 'corporate video', 'podcast video'],
        ogAlt: 'Video Production by Powerhouse Studios, Mangaluru',
      },
    },
    {
      slug: 'video-editing',
      name: 'Video Editing & Post-Production',
      shortName: 'Editing',
      summary: 'Raw footage into polished, platform-ready content.',
      intro: [
        'A great shoot is only the beginning.',
        'Our post-production team transforms raw footage into polished content designed for its intended platform and audience.',
      ],
      capabilitiesIntro: 'Our editing services include:',
      capabilities: [
        'Short-form video editing',
        'Instagram Reels',
        'YouTube videos',
        'Podcast editing',
        'Promotional videos',
        'Brand films',
        'Event highlights',
        'Talking-head videos',
        'Product videos',
        'Corporate videos',
        'Trailer videos',
        'Social media cuts',
        'Motion graphics',
        'Subtitles and captions',
        'Colour correction',
        'Sound design',
        'Music integration',
        'Platform-specific versions',
      ],
      body: [],
      outcome:
        'We can work with footage produced by Powerhouse as well as client-provided footage, depending on the project.',
      related: ['video-production', 'social-media-management', 'event-coverage'],
      faqIds: ['footage', 'entire'],
      image: 'serviceVideoEditing',
      seo: {
        title: 'Video Editing & Post-Production',
        description:
          'Video editing and post-production in Mangaluru: reels, YouTube, podcasts, motion graphics, subtitles, colour correction and sound design, from any footage.',
        keywords: [
          'video editing Mangaluru',
          'post-production',
          'colour correction',
          'reels editing',
        ],
        ogAlt: 'Video Editing & Post-Production by Powerhouse Studios',
      },
    },
    {
      slug: 'photography',
      name: 'Photography',
      shortName: 'Photography',
      summary: 'A visual library brands can use across their marketing.',
      intro: [
        'Visuals play an important role in how people perceive a brand.',
        'Powerhouse provides photography solutions for businesses, campaigns, products, people and events.',
      ],
      capabilitiesIntro: 'Our photography services include:',
      capabilities: [
        'Brand photography',
        'Product photography',
        'Corporate photography',
        'Event photography',
        'Lifestyle photography',
        'Portraits',
        'Social media photography',
        'Campaign photography',
        'Behind-the-scenes photography',
      ],
      body: [],
      outcome:
        'We focus not just on capturing images, but on creating a visual library that brands can use across their marketing and communication.',
      related: ['studio-rentals', 'brand-campaigns', 'event-coverage'],
      faqIds: ['studio', 'outside'],
      image: 'servicePhotography',
      seo: {
        title: 'Brand & Product Photography, Mangaluru',
        description:
          'Brand, product, corporate, event and lifestyle photography in Mangaluru, building a visual library your business can use across its marketing and communication.',
        keywords: ['photography studio Mangaluru', 'product photography', 'brand photography'],
        ogAlt: 'Photography by Powerhouse Studios, Mangaluru',
      },
    },
    {
      slug: 'event-management',
      name: 'Event Management & Production',
      shortName: 'Events',
      summary: 'End-to-end, from planning to execution: a one-stop solution.',
      intro: [
        'Events are experiences.',
        'From planning to execution, Powerhouse provides end-to-end event solutions for brands, businesses and individuals.',
      ],
      capabilitiesIntro: 'Our event capabilities include:',
      capabilities: [
        'Event planning',
        'Event management',
        'Event production',
        'Venue coordination',
        'Stage setup',
        'Event décor',
        'Sound and lighting',
        'DJ',
        'Emcee coordination',
        'Artist coordination',
        'Guest management',
        'Technical production',
        'Event branding',
        'Photography',
        'Videography',
        'Event coverage',
        'Highlight films',
        'On-ground coordination',
      ],
      body: [
        'From intimate celebrations to corporate events and large-scale productions, our team works to ensure that every element comes together smoothly.',
      ],
      outcome: 'Powerhouse is a one-stop solution for complete event management.',
      related: ['event-coverage', 'photography', 'brand-campaigns'],
      faqIds: ['events', 'outside'],
      image: 'serviceEventManagement',
      seo: {
        title: 'Event Management in Mangaluru',
        description:
          'End-to-end event management and production in Mangaluru: planning, venue, stage, décor, sound and lighting, artists, guest management and event coverage.',
        keywords: ['event management Mangaluru', 'event production', 'stage setup', 'event décor'],
        ogAlt: 'Event Management & Production by Powerhouse Studios',
      },
    },
    {
      slug: 'event-coverage',
      name: 'Event Coverage',
      shortName: 'Coverage',
      summary: 'Capture the experience, not just what happened.',
      intro: [
        'An event lasts for a few hours.',
        'The content created from that event can continue working for much longer.',
        'Our event coverage team captures the moments, people, energy and atmosphere of an event and turns them into content that can be used after the event.',
      ],
      capabilitiesIntro: 'Our coverage includes:',
      capabilities: [
        'Event photography',
        'Event videography',
        'Reels',
        'Highlight films',
        'Same-day / fast-turnaround content where applicable',
        'Speaker coverage',
        'Guest interactions',
        'Behind-the-scenes content',
        'Brand activations',
        'Venue and décor coverage',
        'Post-event content',
      ],
      body: [],
      outcome:
        'The objective is not simply to document what happened, but to capture the experience.',
      related: ['event-management', 'video-editing', 'photography'],
      faqIds: ['events', 'outside'],
      image: 'serviceEventCoverage',
      seo: {
        title: 'Event Coverage in Mangaluru',
        description:
          'Event photography and videography in Mangaluru: highlight films, reels, speaker coverage and post-event content that keeps working long after the day is over.',
        keywords: ['event coverage Mangaluru', 'event videography', 'highlight films'],
        ogAlt: 'Event Coverage by Powerhouse Studios, Mangaluru',
      },
    },
    {
      slug: 'studio-rentals',
      name: 'Studio Rentals',
      shortName: 'Studio',
      summary: 'A controlled space for professional content production.',
      intro: ['Powerhouse Studios also provides a creative space for content production.'],
      capabilitiesIntro: 'Our studio environment can support:',
      capabilities: [
        'Video shoots',
        'Photography',
        'Product shoots',
        'Interviews',
        'Talking-head content',
        'Podcasts',
        'Brand shoots',
        'Social media content',
        'Creator shoots',
        'Campaign production',
      ],
      body: [],
      outcome:
        'The studio can be used by brands, creators, agencies and individuals who need a controlled environment for professional content production.',
      related: ['video-production', 'photography', 'video-editing'],
      faqIds: ['studio', 'size'],
      image: 'serviceStudioRentals',
      seo: {
        title: 'Studio Rental in Mangaluru',
        description:
          'Studio rental in Mangaluru for video shoots, photography, product shoots, interviews, podcasts and creator content, in a controlled space built for production.',
        keywords: ['studio rental Mangaluru', 'podcast studio Mangaluru', 'photo studio'],
        ogAlt: 'Studio Rentals at Powerhouse Studios, Mangaluru',
      },
    },
    {
      slug: 'brand-campaigns',
      name: 'Brand Content & Campaigns',
      shortName: 'Campaigns',
      summary: 'Many deliverables, one connected brand story.',
      intro: [
        'Brands often need more than individual pieces of content.',
        'They need campaigns that have a consistent idea, visual identity and communication direction.',
      ],
      capabilitiesIntro: 'Powerhouse can support campaigns through:',
      capabilities: [
        'Campaign concepts',
        'Creative direction',
        'Content strategy',
        'Video production',
        'Photography',
        'Social media content',
        'Digital creatives',
        'Influencer/creator content',
        'Event integration',
        'Campaign execution',
        'Post-campaign content',
      ],
      body: [],
      outcome:
        'We bring multiple creative requirements together so that the campaign feels like one connected brand story.',
      related: ['social-media-management', 'video-production', 'event-management'],
      faqIds: ['entire', 'what'],
      image: 'serviceCampaigns',
      seo: {
        title: 'Brand Content & Campaigns, Mangaluru',
        description:
          'Brand campaigns in Mangaluru: concepts, creative direction, video, photography, social and creator content brought together as one connected brand story.',
        keywords: ['brand campaigns Mangaluru', 'creative direction', 'influencer content'],
        ogAlt: 'Brand Content & Campaigns by Powerhouse Studios',
      },
    },
  ],
} satisfies Content['services']
